### ISSUE TITLE
Should it support `query-params` helper?

### ISSUE THREAD

**Issue by panthony** [peec/ember-transition-helper#9]
I got stuck trying to do a transition with query parameters with this error:

`More context objects were passed than there are dynamic segments for the route: dummyroute`

Not sure why this would not work:

```hbs
{{!-- dummyroute has no path parameter --}}
<span {{action (transition-to "dummyroute" (query-params p=1)}}>
  link
</span>
```

I had to check the source code of both this addon and ember's transitionTo method to understand why.

It actually expect this format:

```hbs
<span {{action (transition-to "dummyroute" (hash queryParams=(hash p=1))}}>
  link
</span>
```

Do you think this addon should intercept and translate object returned by `(query-params)` ? Or at least it should be documented in README.

**Comment by jacobq** [comment]
BTW, even the second form does not work in v0.0.6, because `{{hash}}` uses an `EmptyObject`, which causes problems when [`extractRouteArgs` executes `possibleQueryParams.hashOwnProperty('queryParams')`](https://github.com/emberjs/ember.js/blob/1fe22743e553dbdf9104988b392d0f3a7003caea/packages/ember-routing/lib/utils.js#L12)
